title: hdixon.github.io
name: henry dixon
description: developer homepage
baseurl: /statistical_scientist
lang: en
github_username: hdixon
social:
  name: John Doe
  links:
    - 'https://twitter.com/johndoe'
    - 'https://github.com/johndoe'
remote_theme: siddhantgoel/clean-jekyll-theme
