title: hdixon.me
name: henry dixon
description: developer homepage, listing projects, updates, and other garbage intended just for me. you can read it if you want.
baseurl: /
lang: en
github_username: hdixon
social:
  name: harold dixon
  links:
    - 'https://twitter.com/nothenrydixon'
    - 'https://instagram.com/henry.dixon'
remote_theme: siddhantgoel/clean-jekyll-theme
